[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
name = "ai-waf-v2"
version = "0.1.0"
description = "Transformer-based WAF Classifier"
dependencies = [
    "torch>=2.4.0",
    "transformers",
    "accelerate",
    "pyarrow",
    "pandas",
    "hydra-core",
    "onnx",
    "tensorrt"
]

[project.optional-dependencies]
# For students writing docs, running notebooks, and reading code logic
research = [
    "jupyterlab",
    "ipykernel",
    "matplotlib",
    "seaborn",
    "pandas",
    "pyyaml",
    "ruff",
    "mypy"
]
# For students training models and running the full pipeline
full = [
    "torch",
    "transformers",
    "mlflow",
    "onnxruntime",
    "scikit-learn",
    "onnx"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["stages*", "utils*", "ai-waf-v2*"]